version: "3"
services:
  web:
    build: .
    ports:
     - "3010:3010"
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
     - "5672:5672"
     - "15672:15672"
    volumes:
     - ./docker-volumes/rabbitmq:/var/lib/rabbitmq
  mongodb:
    image: "mongo"
    volumes:
     - ./docker-volume/mongo:/data/db