version: "3"
services:
  web:
    build: .
    ports:
     - "3010:3010"
    env_file:
     - sauron_variables.env
    volumes:
     - ${PWD}/routingKeysConfig.json:/usr/src/app/routingKeysConfig.json
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
     - "5672:5672"
     - "15672:15672"
    volumes:
     - ./docker-volumes/rabbitmq:/var/lib/rabbitmq
  mongodb:
    image: "mongo"
    volumes:
     - ./docker-volumes/mongo:/data/db